# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
    # Especifica a box "ubuntu/focal64"
    config.vm.box = "ubuntu/focal64"
    # Especifica o provedor (VirtualBox neste exemplo)
    config.vm.provider "virtualbox" do |vb|
      vb.name=" VM03"
      #vb.memory = 2048
      #vb.cpus = 2
    end
  
    # Configura uma rede privada usando fixo
    config.vm.network "private_network", ip: "192.168.56.12",auto_config:false;
    #configuta uma rede de ip publico DHCP
    config.vm.network "public_network", type: "dhcp"
    # Configura um redirecionamento de porta

    config.vm.network "forwarded_port",guest: 80, host: 8088
  
    # Provisão usando um shell script
    config.vm.provision "shell", inline: <<-SHELL
      # Ative o redirecionamento de pacotes IPv4
      echo 'net.ipv4.ip_forward=1' | sudo tee -a /etc/sysctl.conf
      echo 1 | sudo tee /proc/sys/net/ipv4/ip_forward
      #redirecionamento de internet
      sudo iptables -t nat -A POSTROUTING -o enp0s3 -j MASQUERADE
      #instalar o modulo para usar o ifconfig
      sudo apt install net-tools
      #config interface
      sudo ifconfig enp0s8 up
      #config enp0s8
      sudo ip addr add 192.168.56.12/24 dev enp0s8
      #vm1 rota
      sudo ip route add 192.168.56.10 via 192.168.56.12
      #vm2 rota
     	sudo ip route add 192.168.56.11 via 192.168.56.12 

    SHELL
  end
