# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
    # Especifica a box "ubuntu/focal64"
    config.vm.box = "ubuntu/focal64"
    # Especifica o provedor (VirtualBox neste exemplo)
    config.vm.provider "virtualbox" do |vb|
      vb.name=" VM03"
      vb.memory = 2048
      vb.cpus = 2
    end
  
    # Configura uma rede privada usando fixo
    config.vm.network "private_network", ip: "192.168.56.12",
    virtualbox__internet:"eth0";
    #configuta uma rede de ip publico DHCP
    config.vm.network "public_network",
    use_dhcp_assigned_default_route: true,
    virtualbox__internet:"eth1"
  
    # Configura uma pasta sincronizada
    config.vm.synced_folder "./shared_folder", "/vagrant_shared"
    # Configura um redirecionamento de porta
    config.vm.network "forwarded_port",guest: 80, host: 8080
  
    # Provisão usando um shell script
    config.vm.provision "shell", inline: <<-SHELL
    apt-get update
    routes del default
    routes add default gw mygatewayip eth1
    SHELL
  end