
# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
    # Especifica a box "ubuntu/focal64"
    config.vm.box = "ubuntu/focal64"
    # Especifica o provedor (VirtualBox neste exemplo)
    config.vm.provider "virtualbox" do |vb|
      vb.name="VM1"
     # vb.memory = 2048
     # vb.cpus = 2
    end
  
    # Configura uma rede privada usando fixo
    config.vm.network "private_network", ip: "192.168.56.10"
  
    # Configura uma pasta sincronizada
    config.vm.synced_folder "./shared_folder", "/var/www/html"
    # Configura um redirecionamento de porta
    #config.vm.network "forwarded_port", guest: 80, host: 8080
  
    # Provisão usando um shell script
    config.vm.provision "shell", inline: <<-SHELL
    #da update nos repositorios e baixa o apache para ser servidor
    apt  update
    apt  install -y apache2
    #define a rota padrão que a vm2 deve correr para comunicar com a vm3
    sudo ip route add default via 192.168.56.12
    SHELL
  end
